import { Category, Product } from "@/types";
import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  FileText,
  Users,
  Settings,
  Layers,
} from "lucide-react";

export const NAV_LINKS = [
  {
    title: "Dashboard",
    url: "/",
    icon: LayoutDashboard,
  },
  {
    title: "Sales(POS)",
    url: "/pos",
    icon: ShoppingCart,
  },
  {
    title: "Products",
    url: "/products",
    icon: Package,
  },
  {
    title: "Categories",
    url: "/categories",
    icon: Layers,
  },
  {
    title: "Reports",
    url: "/reports",
    icon: FileText,
  },
  {
    title: "Users",
    url: "/users",
    icon: Users,
  },
  {
    title: "Settings",
    url: "/settings",
    icon: Settings,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Potato",
    category: "Grocery",
    price: 0.34,
    stock: 30,
  },
  {
    id: 2,
    name: "Onion",
    category: "Grocery",
    price: 0.71,
    stock: 50,
  },
  {
    id: 3,
    name: "Cooking Oil",
    category: "General",
    price: 1.57,
    stock: 15,
  },
  {
    id: 4,
    name: "Rice (1kg)",
    category: "Grocery",
    price: 1.14,
    stock: 100,
  },
  {
    id: 5,
    name: "Coffee Mix",
    category: "Beverage",
    price: 0.1,
    stock: 200,
  },
  {
    id: 6,
    name: "Coca Cola",
    category: "Beverage",
    price: 0.43,
    stock: 45,
  },
  {
    id: 7,
    name: "Soap",
    category: "Household",
    price: 0.23,
    stock: 60,
  },
  {
    id: 8,
    name: "Toothpaste",
    category: "Household",
    price: 0.63,
    stock: 25,
  },
  {
    id: 9,
    name: "Instant Noodles",
    category: "Grocery",
    price: 0.17,
    stock: 120,
  },
  {
    id: 10,
    name: "Eggs (10pcs)",
    category: "Grocery",
    price: 0.86,
    stock: 40,
  },
  {
    id: 11,
    name: "Apples",
    category: "Grocery",
    price: 0.87,
    stock: 20,
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 1,
    name: "Grocery",
    description: "Essential daily food items",
    productCount: 7,
    status: "active",
    createdAt: "2026-02-01",
  },
  {
    id: 2,
    name: "Beverage",
    description: "Drinks and refreshments",
    productCount: 2,
    status: "active",
    createdAt: "2026-02-03",
  },
  {
    id: 3,
    name: "Household",
    description: "Cleaning and home supplies",
    productCount: 2,
    status: "inactive",
    createdAt: "2026-02-05",
  },
  {
    id: 4,
    name: "Snacks",
    description: "Chips, noodles, and quick bites",
    productCount: 5,
    status: "active",
    createdAt: "2026-02-06",
  },
  {
    id: 5,
    name: "Personal Care",
    description: "Toiletries and hygiene products",
    productCount: 4,
    status: "active",
    createdAt: "2026-02-07",
  },
  {
    id: 6,
    name: "Fruits & Vegetables",
    description: "Fresh produce and organic items",
    productCount: 6,
    status: "active",
    createdAt: "2026-02-08",
  },
  {
    id: 7,
    name: "Frozen Foods",
    description: "Frozen meat, snacks, and ice cream",
    productCount: 0,
    status: "archived",
    createdAt: "2026-02-09",
  },
  {
    id: 8,
    name: "Bakery",
    description: "Bread, cakes, and baked goods",
    productCount: 3,
    status: "inactive",
    createdAt: "2026-02-10",
  },
]
